# =============================================================================
# NixOS Configuration Skeleton
# Framework 13 AMD 7840U -- KDE Plasma 6 + GNOME -- Developer Workstation
# =============================================================================
#
# This is a SKELETON showing how all pieces fit together. It is meant to be
# split into the modular file structure described in architecture.md, but is
# presented as a single file for readability.
#
# Channel strategy: stable base (nixos-24.11) + selective unstable overlay.
# Dual DE: KDE Plasma 6 and GNOME enabled simultaneously.
#
# To use: copy into the modular structure, split by section comments, and
# adjust values marked with TODO.
#
# =============================================================================

# --- flake.nix (entry point) ---
# This would be the top-level flake.nix file.
/*
{
  description = "NixOS configuration for Framework 13 AMD -- stable + unstable overlay";

  inputs = {
    # Primary: stable channel (upgrade to nixos-25.05 when released ~May 2026)
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";

    # Secondary: unstable for selective package overrides (Citrix, etc.)
    nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Home Manager pinned to stable branch
    home-manager = {
      url = "github:nix-community/home-manager/release-24.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Framework laptop hardware support
    nixos-hardware.url = "github:NixOS/nixos-hardware";

    # Declarative disk partitioning (optional, for reproducible installs)
    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Declarative Flatpak management
    nix-flatpak.url = "github:guyber/nix-flatpak";
  };

  outputs = {
    self,
    nixpkgs,
    nixpkgs-unstable,
    home-manager,
    nixos-hardware,
    disko,
    nix-flatpak,
    ...
  }: let
    system = "x86_64-linux";

    # Import unstable nixpkgs for selective use
    pkgs-unstable = import nixpkgs-unstable {
      inherit system;
      config.allowUnfree = true;
    };
  in {
    nixosConfigurations.framework = nixpkgs.lib.nixosSystem {
      inherit system;

      # Pass unstable pkgs to all modules via specialArgs
      specialArgs = { inherit pkgs-unstable; };

      modules = [
        # Hardware support for Framework 13 AMD 7040 series
        nixos-hardware.nixosModules.framework-13-7040-amd

        # Flatpak declarative management
        nix-flatpak.nixosModules.nix-flatpak

        # Main system configuration (everything below)
        ./hosts/framework/configuration.nix
        ./hosts/framework/hardware-configuration.nix  # Generated by nixos-generate-config

        # Home Manager as NixOS module
        home-manager.nixosModules.home-manager
        {
          home-manager.useGlobalPkgs = true;
          home-manager.useUserPackages = true;
          home-manager.extraSpecialArgs = { inherit pkgs-unstable; };
          home-manager.users.zervin = import ./home/zervin/default.nix;
        }
      ];
    };

    # =========================================================================
    # Example devShell for this config repo itself (optional)
    # =========================================================================
    devShells.${system}.default = nixpkgs.legacyPackages.${system}.mkShell {
      packages = with nixpkgs.legacyPackages.${system}; [
        nil           # Nix LSP for editor integration
        nixfmt-rfc-style  # Nix formatter
        statix        # Nix linter
      ];
      shellHook = ''
        echo "NixOS config dev environment loaded"
        echo "  nil    - Nix language server"
        echo "  nixfmt - Nix formatter"
        echo "  statix - Nix linter"
      '';
    };
  };
}
*/

# =============================================================================
# Below is the combined configuration.nix content (would be split into modules)
# =============================================================================
{ config, pkgs, pkgs-unstable, lib, ... }:

{
  # ===========================================================================
  # SECTION: Nix Settings
  # ===========================================================================
  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      # Deduplicate identical files in the store
      auto-optimise-store = true;
      # Limit build parallelism to avoid hogging the system
      max-jobs = lib.mkDefault 8;
      # Warn if a build command is using nix-env (anti-creep)
      warn-dirty = false;
    };

    # Automatic garbage collection -- the primary anti-creep mechanism
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 30d";
    };
  };

  # Allow unfree packages (VS Code, Chrome, Steam, Zoom, Citrix, Discord, etc.)
  nixpkgs.config.allowUnfree = true;

  # ===========================================================================
  # SECTION: Boot (LUKS + systemd-boot)
  # ===========================================================================
  boot = {
    loader = {
      systemd-boot = {
        enable = true;
        # Cap boot menu to 5 most recent generations (anti-creep for boot menu)
        configurationLimit = 5;
      };
      efi.canTouchEfiVariables = true;
    };

    # LUKS configuration (also in hardware-configuration.nix, shown here for clarity)
    initrd.luks.devices."cryptroot" = {
      # TODO: Replace with actual UUID from `blkid /dev/nvme0n1p2`
      device = "/dev/disk/by-uuid/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
      allowDiscards = true;  # Enable TRIM for SSD performance
    };

    # Kernel parameters
    kernelParams = [
      "quiet"
      "splash"
    ];

    # Plymouth for graphical boot (optional)
    plymouth.enable = true;
  };

  # ===========================================================================
  # SECTION: Filesystem (Btrfs subvolumes)
  # ===========================================================================
  # NOTE: Most of this is auto-generated in hardware-configuration.nix.
  # Shown here for documentation purposes.
  /*
  fileSystems = {
    "/" = {
      device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };
    "/home" = {
      device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };
    "/nix" = {
      device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/YYYY-YYYY";  # EFI partition UUID
      fsType = "vfat";
    };
  };
  */

  # Use zram for swap (better than swap file for 54GB RAM)
  zramSwap = {
    enable = true;
    memoryPercent = 25;  # 25% of RAM = ~13.5GB zram swap
  };

  # ===========================================================================
  # SECTION: Hardware -- Framework 13 AMD
  # ===========================================================================
  # Most is handled by nixos-hardware.nixosModules.framework-13-7040-amd
  # but we add explicit config for clarity and overrides.

  hardware = {
    # AMD GPU (Radeon 780M integrated)
    graphics = {
      enable = true;
      enable32Bit = true;  # Required for Steam and 32-bit games
      # Mesa drivers (RADV Vulkan, VA-API) are included automatically
    };

    # Bluetooth
    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };

    # Sensor support (ambient light, accelerometer)
    sensor.iio.enable = true;

    # CPU microcode
    cpu.amd.updateMicrocode = true;
  };

  # Firmware updates (Framework uses fwupd extensively)
  services.fwupd.enable = true;

  # ===========================================================================
  # SECTION: Networking
  # ===========================================================================
  networking = {
    hostName = "framework";  # TODO: Set your hostname
    networkmanager.enable = true;

    # Firewall (enabled by default on NixOS)
    firewall = {
      enable = true;
      # Allow Tailscale, Syncthing, KDE Connect
      trustedInterfaces = [ "tailscale0" ];
      allowedTCPPorts = [
        22000  # Syncthing
      ];
      allowedUDPPorts = [
        22000  # Syncthing
        21027  # Syncthing discovery
      ];
      # KDE Connect ports
      allowedTCPPortRanges = [
        { from = 1714; to = 1764; }
      ];
      allowedUDPPortRanges = [
        { from = 1714; to = 1764; }
      ];
    };
  };

  # ===========================================================================
  # SECTION: Desktop Environment -- KDE Plasma 6 + GNOME (Dual DE)
  # ===========================================================================

  # --- KDE Plasma 6 ---
  services.desktopManager.plasma6.enable = true;

  # --- GNOME ---
  services.xserver.desktopManager.gnome.enable = true;

  # --- Display Manager: SDDM serves both DEs ---
  services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
  };

  # Default session (SDDM also remembers last used per-user)
  services.displayManager.defaultSession = "plasma";  # or "gnome"

  # --- GNOME Online Accounts (the key reason for GNOME) ---
  services.gnome.gnome-online-accounts.enable = true;

  # --- XDG portals for Wayland (both DEs need their portal) ---
  xdg.portal = {
    enable = true;
    extraPortals = [
      pkgs.xdg-desktop-portal-kde
      pkgs.xdg-desktop-portal-gnome
    ];
    # Each DE session uses its own portal based on $XDG_CURRENT_DESKTOP
    config = {
      common = {
        default = [ "kde" "gnome" ];
      };
    };
  };

  # ===========================================================================
  # SECTION: Audio -- PipeWire
  # ===========================================================================
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;    # PulseAudio compatibility
    wireplumber.enable = true;
  };
  # Disable PulseAudio (replaced by PipeWire)
  hardware.pulseaudio.enable = false;

  # ===========================================================================
  # SECTION: Services
  # ===========================================================================

  # --- Docker ---
  virtualisation.docker = {
    enable = true;
    # Docker Compose v2 is included by default
  };

  # --- Podman ---
  virtualisation.podman = {
    enable = true;
    # Do NOT enable dockerCompat when Docker is also enabled
    defaultNetwork.settings.dns_enabled = true;  # Aardvark DNS equivalent
  };

  # --- Ollama (AI/ML) ---
  services.ollama = {
    enable = true;
    # acceleration = "rocm";  # For AMD GPU -- limited support on 780M iGPU
    # Cloud-proxied models do not need GPU acceleration
  };

  # --- Tailscale VPN ---
  services.tailscale = {
    enable = true;
    useRoutingFeatures = "client";  # or "both" if acting as exit node
  };

  # --- Syncthing ---
  services.syncthing = {
    enable = true;
    user = "zervin";
    dataDir = "/home/zervin";
    configDir = "/home/zervin/.config/syncthing";
  };

  # --- Printing (CUPS + Avahi) ---
  services.printing.enable = true;
  services.avahi = {
    enable = true;
    nssmdns4 = true;  # .local hostname resolution
    openFirewall = true;
  };

  # --- Power Management ---
  services.power-profiles-daemon.enable = true;

  # --- smartmontools ---
  services.smartd.enable = true;

  # --- UDISKS2 (automounting) ---
  services.udisks2.enable = true;

  # ===========================================================================
  # SECTION: Flatpak
  # ===========================================================================
  services.flatpak.enable = true;

  # Declarative Flatpak management via nix-flatpak:
  # services.flatpak = {
  #   packages = [
  #     "eu.betterbird.Betterbird"     # Betterbird email client
  #     "net.mkiol.SpeechNote"         # Speech Note
  #     # Insync only needed for KDE sessions (GNOME uses Online Accounts):
  #     # "com.insynchq.insync"
  #   ];
  #   remotes = [
  #     { name = "flathub"; location = "https://flathub.org/repo/flathub.flatpakrepo"; }
  #   ];
  # };

  # ===========================================================================
  # SECTION: Gaming
  # ===========================================================================
  programs.steam = {
    enable = true;
    remotePlay.openFirewall = true;
    gamescopeSession.enable = false;
  };

  programs.gamemode.enable = true;

  # ===========================================================================
  # SECTION: Security
  # ===========================================================================
  security = {
    # AppArmor (matches Debian setup)
    apparmor = {
      enable = true;
      killUnconfinedConfinables = false;
      packages = with pkgs; [
        apparmor-profiles  # Community AppArmor profiles
      ];
    };

    # Audit subsystem (optional -- uncomment for security monitoring)
    # audit = {
    #   enable = true;
    #   rules = [
    #     "-a exit,always -F arch=b64 -S execve"
    #   ];
    # };
    # auditd.enable = true;

    # Polkit for privilege escalation (KDE and GNOME both use this)
    polkit.enable = true;

    # Real-time kit for PipeWire
    rtkit.enable = true;
  };

  # ===========================================================================
  # SECTION: Users
  # ===========================================================================
  users.users.zervin = {
    isNormalUser = true;
    description = "zervin";  # TODO: Set display name
    extraGroups = [
      "wheel"           # sudo access
      "networkmanager"  # Network management
      "docker"          # Docker without sudo
      "video"           # GPU access
      "audio"           # Audio access
      "input"           # Input devices
      "lp"              # Printing
    ];
    # TODO: Set initial password or use hashedPassword
    # initialPassword = "changeme";  # Change on first login
  };

  # ===========================================================================
  # SECTION: System Packages
  # ===========================================================================
  environment.systemPackages = with pkgs; [
    # --- System utilities ---
    vim
    wget
    curl
    git
    htop
    lm_sensors
    pciutils
    usbutils
    lsof
    file
    unzip
    tree

    # --- Filesystem tools ---
    btrfs-progs
    compsize        # btrfs compression stats

    # --- Networking ---
    inetutils

    # --- Work-critical: Citrix from UNSTABLE (version lag on stable) ---
    # Citrix Workspace has known libwebkitgtk2 issues on older stable.
    # Pulling from unstable ensures latest version with correct deps.
    pkgs-unstable.citrix_workspace

    # --- Work-critical: Zoom ---
    zoom-us

    # --- Work-critical: ZoomVDI ---
    # TODO: Investigate if this exists in nixpkgs.
    # Run `nix search nixpkgs#zoomvdi` to check.
    # If not available, options:
    #   1. Check if zoom-us includes VDI support natively
    #   2. Wrap upstream .deb in buildFHSUserEnv
    #   3. Flatpak
    # pkgs.zoomvdi  # Uncomment if available

    # --- KDE extras ---
    kdePackages.kontact
    kdePackages.merkuro
    kdePackages.plasma-vault
    kdePackages.kdeconnect-kde
    kdePackages.dolphin-plugins
    kdePackages.kate
    kdePackages.ark

    # --- GNOME extras (for GNOME sessions) ---
    gnome-online-accounts
    evolution
    evolution-data-server
    gnome-calendar
    gnome-contacts

    # --- Framework-specific ---
    framework-tool  # Framework laptop CLI tool
  ];

  # ===========================================================================
  # SECTION: Programs (system-wide)
  # ===========================================================================
  programs = {
    # KDE Partition Manager
    partition-manager.enable = true;

    # Firefox (system-wide policies possible)
    firefox = {
      enable = true;
      package = pkgs.firefox-esr;
    };

    # Enable dconf (needed for GNOME apps and some GTK apps under KDE)
    dconf.enable = true;
  };

  # ===========================================================================
  # SECTION: Locale and Time
  # ===========================================================================
  time.timeZone = "America/New_York";  # TODO: Set your timezone

  i18n.defaultLocale = "en_US.UTF-8";

  # ===========================================================================
  # SECTION: System Version
  # ===========================================================================
  system.stateVersion = "24.11";  # Do not change after initial install
}

# =============================================================================
# HOME MANAGER CONFIGURATION (home/zervin/default.nix)
# =============================================================================
# This would be a separate file imported by Home Manager.
/*
{ config, pkgs, pkgs-unstable, ... }:

{
  home.username = "zervin";
  home.homeDirectory = "/home/zervin";
  home.stateVersion = "24.11";  # Do not change after initial setup

  # =========================================================================
  # User Packages
  # =========================================================================
  home.packages = with pkgs; [
    # --- Browsers ---
    brave
    google-chrome

    # --- Communication ---
    discord
    teams-for-linux       # Community Teams client
    # zoom-us and citrix_workspace are in system packages (work-critical)

    # --- Editors ---
    vscode
    zed-editor
    jetbrains-toolbox

    # --- Languages & Runtimes (globally installed) ---
    # NOTE: Prefer devShells for project-specific toolchains.
    # Only install globally what you use across many projects.
    nodejs_22
    python313
    uv                    # Python package manager
    rustup                # Rust toolchain manager
    go
    jdk21                 # Java (Zulu or OpenJDK)
    bun                   # JS runtime

    # --- Build Tools ---
    gnumake
    cmake
    autoconf
    automake
    gcc
    pkg-config

    # --- CLI Tools ---
    gh                    # GitHub CLI
    google-cloud-sdk      # gcloud

    # --- Creative ---
    gimp
    inkscape
    bambu-studio          # 3D printing
    openscad              # Parametric 3D modeling

    # --- Media ---
    vlc

    # --- Office ---
    libreoffice

    # --- Notes / PKM ---
    obsidian
    logseq

    # --- File Sync ---
    syncthingtray         # SyncthingTray for KDE

    # --- Networking ---
    ktailctl              # Tailscale KDE GUI

    # --- Utilities ---
    upscayl               # AI image upscaling
    nicotine-plus         # Soulseek client

    # --- AI/ML CLI ---
    # claude-code: install via `npm install -g @anthropic-ai/claude-code`
    #   or use: nix shell nixpkgs#nodePackages.npm -c npm install -g ...
    # opencode: install via `go install` or download binary
  ];

  # =========================================================================
  # Shell Configuration
  # =========================================================================
  programs.bash = {
    enable = true;
    shellAliases = {
      ll = "ls -la";
      gs = "git status";
      gd = "git diff";
      dc = "docker compose";

      # NixOS rebuild shortcuts
      nr = "sudo nixos-rebuild switch --flake ~/projects/nixos#framework";
      nrb = "sudo nixos-rebuild build --flake ~/projects/nixos#framework";
      nrt = "sudo nixos-rebuild test --flake ~/projects/nixos#framework";

      # Update flake inputs then rebuild
      nu = "nix flake update --flake ~/projects/nixos && sudo nixos-rebuild switch --flake ~/projects/nixos#framework";

      # Garbage collection
      ngc = "sudo nix-collect-garbage --delete-older-than 30d";

      # Store info
      nstore = "echo \"Store size: $(du -sh /nix/store | cut -f1)\" && echo \"Store paths: $(nix path-info --all | wc -l)\"";
    };
    initExtra = ''
      # Bun
      export BUN_INSTALL="$HOME/.bun"
      export PATH="$BUN_INSTALL/bin:$PATH"

      # Go
      export GOPATH="$HOME/go"
      export PATH="$GOPATH/bin:$PATH"

      # Rust (managed by rustup)
      export PATH="$HOME/.cargo/bin:$PATH"
    '';
  };

  # =========================================================================
  # Git Configuration
  # =========================================================================
  programs.git = {
    enable = true;
    userName = "zervin";            # TODO: Set your name
    userEmail = "zervin@example.com"; # TODO: Set your email
    extraConfig = {
      init.defaultBranch = "main";
      pull.rebase = true;
      push.autoSetupRemote = true;
    };
  };

  # =========================================================================
  # VS Code
  # =========================================================================
  programs.vscode = {
    enable = true;
    # Declarative extension management (optional):
    # extensions = with pkgs.vscode-extensions; [
    #   ms-python.python
    #   rust-lang.rust-analyzer
    #   golang.go
    # ];
  };

  # =========================================================================
  # direnv (optional but recommended for automatic devShell activation)
  # =========================================================================
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;  # Better caching for nix develop
  };

  # =========================================================================
  # XDG User Directories
  # =========================================================================
  xdg.userDirs = {
    enable = true;
    createDirectories = true;
  };

  # =========================================================================
  # Home Manager Self-Management
  # =========================================================================
  programs.home-manager.enable = true;
}
*/

# =============================================================================
# EXAMPLE DEVSHELL: Flutter Project (~/projects/my-flutter-app/flake.nix)
# =============================================================================
# This shows how to create a project-specific dev environment that does NOT
# pollute the global system. cd into the project, run `nix develop`, and
# get Flutter + Dart + Android SDK. Exit the shell, they are gone.
#
# With direnv enabled (see Home Manager config above), just add a file
# `.envrc` containing `use flake` in the project root, and the devShell
# activates automatically on cd.
/*
{
  description = "Flutter development environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
          config.android_sdk.accept_license = true;
        };

        # Android SDK configuration
        androidComposition = pkgs.androidenv.composeAndroidPackages {
          platformVersions = [ "34" "33" ];
          buildToolsVersions = [ "34.0.0" ];
          includeEmulator = false;
          includeSystemImages = false;
          includeSources = false;
        };
      in {
        devShells.default = pkgs.mkShell {
          packages = with pkgs; [
            flutter
            dart
            jdk21
            androidComposition.androidsdk
          ];

          ANDROID_HOME = "${androidComposition.androidsdk}/libexec/android-sdk";
          JAVA_HOME = "${pkgs.jdk21}";

          shellHook = ''
            echo "Flutter dev environment loaded"
            echo "  Flutter: $(flutter --version | head -1)"
            echo "  Dart:    $(dart --version 2>&1)"
            echo "  Java:    $(java --version 2>&1 | head -1)"
          '';
        };
      }
    );
}
*/

# =============================================================================
# EXAMPLE DEVSHELL: Node.js Project (~/projects/my-node-app/flake.nix)
# =============================================================================
/*
{
  description = "Node.js project dev environment";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      devShells.${system}.default = pkgs.mkShell {
        packages = with pkgs; [
          nodejs_22
          bun
          nodePackages.typescript
          nodePackages.prettier
        ];
        shellHook = ''
          echo "Node $(node --version) | Bun $(bun --version) | TS $(tsc --version)"
        '';
      };
    };
}
*/

# =============================================================================
# EXAMPLE DEVSHELL: Python ML Project (~/projects/my-ml-project/flake.nix)
# =============================================================================
/*
{
  description = "Python ML project dev environment";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.11";

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      devShells.${system}.default = pkgs.mkShell {
        packages = with pkgs; [
          python313
          uv
          # uv manages the virtualenv and dependencies; no need to
          # install Python packages in Nix. Just `uv sync` in the project.
        ];
        shellHook = ''
          echo "Python $(python3 --version) | uv $(uv --version)"
          # Auto-activate venv if it exists
          if [ -d .venv ]; then
            source .venv/bin/activate
          fi
        '';
      };
    };
}
*/

# =============================================================================
# NOTES FOR THE USER
# =============================================================================
#
# 1. This is a SKELETON. It will not build as-is. Split it into the modular
#    structure from architecture.md, fix all TODO markers, and remove the
#    block comments around the flake.nix and home-manager sections.
#
# 2. After first install, run `nixos-generate-config --root /mnt` and use
#    the generated hardware-configuration.nix. Do NOT hand-write it.
#
# 3. The `system.stateVersion` and `home.stateVersion` should match the
#    NixOS version at time of initial install. Never change these after.
#
# 4. Channel strategy:
#      - nixpkgs (stable 24.11) is the base for everything
#      - nixpkgs-unstable is available as `pkgs-unstable` for specific overrides
#      - Only use pkgs-unstable when stable has a concrete bug/version issue
#      - Document WHY in a comment next to every pkgs-unstable reference
#
# 5. Anti-creep rules:
#      - NEVER use `nix-env -i` -- always edit a .nix file
#      - Use `nix shell nixpkgs#pkg` for ephemeral one-off use
#      - Use devShells (flake.nix per project) for project toolchains
#      - Run `ngc` alias periodically (or rely on weekly auto-GC)
#      - Keep configurationLimit = 5 to keep boot menu clean
#
# 6. Build and test without switching:
#      sudo nixos-rebuild build --flake .#framework
#
# 7. Switch to a new configuration:
#      sudo nixos-rebuild switch --flake .#framework
#
# 8. Rollback:
#      sudo nixos-rebuild switch --rollback
#
# 9. Update packages:
#      nix flake update                        # Update all inputs
#      nix flake update nixpkgs                # Update only stable
#      nix flake update nixpkgs-unstable       # Update only unstable
#      sudo nixos-rebuild switch --flake .#framework
#
# 10. Search for packages:
#      nix search nixpkgs#<name>
#      Or visit https://search.nixos.org/packages
#
# 11. Unfree packages (VS Code, Chrome, Steam, Zoom, Citrix, Discord,
#     Obsidian, JetBrains, etc.) require `nixpkgs.config.allowUnfree = true`.
#
# 12. For packages NOT in nixpkgs (Betterbird, Speech Note):
#     Use Flatpak. Enable via `services.flatpak.enable = true` and
#     install with `flatpak install flathub <app-id>`.
#
# 13. Dual DE: Both KDE and GNOME are enabled. At SDDM login, pick your
#     session from the dropdown. GNOME Online Accounts replaces Insync
#     for Google Drive / OneDrive when in GNOME sessions.
#
# =============================================================================
